sonar.projectKey=L01-GitFit_gitfit-webservice
sonar.organization=l01-gitfit

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.d.ts,**/*.spec.ts,**/prisma/prisma.service.mock.ts,**/main.ts,**/*.module.ts

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.typescript.tsconfigPath=tsconfig.json
